# Generated by Django 3.0.5 on 2020-04-21 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreferredShirt',
            new_name='PreferredShift',
        ),
    ]
