# Generated by Django 3.0.5 on 2020-04-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_auto_20200421_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('birthdate', models.CharField(max_length=255)),
                ('birth_place', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('civil_status', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('social_media_accounts', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=255)),
                ('landline_number', models.CharField(max_length=255)),
                ('home_address', models.CharField(max_length=255)),
            ],
        ),
    ]
