# Generated by Django 3.0.5 on 2020-04-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_studentpersonalinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhereDidYouHearUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WhyDidYouChooseUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why', models.CharField(max_length=255)),
            ],
        ),
    ]
