# Generated by Django 3.0.5 on 2020-04-21 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_wheredidyouhearus_whydidyouchooseus'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpersonalinformation',
            name='classification',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admission.StudentClassification'),
        ),
    ]
