# Generated by Django 3.0.5 on 2020-04-21 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_studentpersonalinformation_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpersonalinformation',
            name='classification',
        ),
    ]
