# Generated by Django 3.0.5 on 2020-04-21 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_remove_studentpersonalinformation_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpersonalinformation',
            name='stud_classification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admission.StudentClassification'),
        ),
    ]
