# Generated by Django 3.0.5 on 2020-04-21 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_studentpersonalinformation_stud_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpersonalinformation',
            name='stud_program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admission.Programs'),
        ),
        migrations.AddField(
            model_name='studentpersonalinformation',
            name='stud_shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admission.PreferredShift'),
        ),
        migrations.AddField(
            model_name='studentpersonalinformation',
            name='stud_year_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admission.YearLevel'),
        ),
    ]
