# Generated by Django 3.0.5 on 2020-04-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_auto_20200422_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferredshift',
            name='shift_title',
            field=models.CharField(max_length=3),
        ),
    ]
