# Generated by Django 3.0.5 on 2020-04-22 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0009_auto_20200422_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpersonalinformation',
            name='where_hear_us',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admission.WhereDidYouHearUs'),
        ),
        migrations.AddField(
            model_name='studentpersonalinformation',
            name='why_choose_us',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admission.WhyDidYouChooseUs'),
        ),
    ]
