# Generated by Django 3.0.5 on 2020-04-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0011_auto_20200425_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpersonalinformation',
            name='connectivity',
            field=models.CharField(default='limited connectivity', max_length=255),
        ),
    ]
