# Generated by Django 3.0.5 on 2020-04-30 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0012_studentpersonalinformation_connectivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpersonalinformation',
            name='date_registered',
            field=models.DateField(default=datetime.date(2020, 4, 30)),
        ),
    ]
