# Generated by Django 3.0.5 on 2020-04-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0013_studentpersonalinformation_date_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpersonalinformation',
            name='date_registered',
            field=models.DateField(auto_now_add=True),
        ),
    ]
