# Generated by Django 3.0.5 on 2020-05-01 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0014_auto_20200430_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='studentpersonalinformation',
            name='school_year',
            field=models.CharField(default='2020-2021', max_length=255),
        ),
        migrations.CreateModel(
            name='SeniorHighSchool_StudentPersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shs_last_name', models.CharField(max_length=255)),
                ('shs_first_name', models.CharField(max_length=255)),
                ('shs_middle_name', models.CharField(max_length=255)),
                ('shs_birthdate', models.CharField(max_length=255)),
                ('shs_birth_place', models.CharField(max_length=255)),
                ('shs_religion', models.CharField(blank=True, max_length=255)),
                ('shs_nationality', models.CharField(max_length=255)),
                ('shs_gender', models.CharField(max_length=255)),
                ('shs_civil_status', models.CharField(max_length=255)),
                ('shs_email_address', models.CharField(max_length=255)),
                ('shs_social_media_accounts', models.CharField(blank=True, max_length=255)),
                ('shs_mobile_number', models.CharField(max_length=255)),
                ('shs_landline_number', models.CharField(blank=True, max_length=255)),
                ('shs_home_address', models.CharField(max_length=255)),
                ('connectivity', models.CharField(default='limited connectivity', max_length=255)),
                ('school_year', models.CharField(default='2020-2021', max_length=255)),
                ('shs_date_registered', models.DateField(auto_now_add=True)),
                ('shs_stud_classification', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admission.StudentClassification')),
                ('shs_stud_grade_level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admission.GradeLevel')),
                ('shs_stud_strand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admission.Programs')),
                ('where_hear_us', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admission.WhereDidYouHearUs')),
                ('why_choose_us', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admission.WhyDidYouChooseUs')),
            ],
        ),
        migrations.CreateModel(
            name='JuniorHighSchool_StudentPersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jhs_last_name', models.CharField(max_length=255)),
                ('jhs_first_name', models.CharField(max_length=255)),
                ('jhs_middle_name', models.CharField(max_length=255)),
                ('jhs_birthdate', models.CharField(max_length=255)),
                ('jhs_birth_place', models.CharField(max_length=255)),
                ('jhs_religion', models.CharField(blank=True, max_length=255)),
                ('jhs_nationality', models.CharField(max_length=255)),
                ('jhs_gender', models.CharField(max_length=255)),
                ('jhs_civil_status', models.CharField(max_length=255)),
                ('jhs_email_address', models.CharField(max_length=255)),
                ('jhs_social_media_accounts', models.CharField(blank=True, max_length=255)),
                ('jhs_mobile_number', models.CharField(max_length=255)),
                ('jhs_landline_number', models.CharField(blank=True, max_length=255)),
                ('jhs_home_address', models.CharField(max_length=255)),
                ('connectivity', models.CharField(default='limited connectivity', max_length=255)),
                ('school_year', models.CharField(default='2020-2021', max_length=255)),
                ('jhs_date_registered', models.DateField(auto_now_add=True)),
                ('jhs_stud_classification', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admission.StudentClassification')),
                ('jhs_stud_grade_level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admission.GradeLevel')),
                ('where_hear_us', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admission.WhereDidYouHearUs')),
                ('why_choose_us', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admission.WhyDidYouChooseUs')),
            ],
        ),
        migrations.CreateModel(
            name='Elementary_StudentPersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementary_last_name', models.CharField(max_length=255)),
                ('elementary_first_name', models.CharField(max_length=255)),
                ('elementary_middle_name', models.CharField(max_length=255)),
                ('elementary_birthdate', models.CharField(max_length=255)),
                ('elementary_birth_place', models.CharField(max_length=255)),
                ('elementary_religion', models.CharField(blank=True, max_length=255)),
                ('elementary_nationality', models.CharField(max_length=255)),
                ('elementary_gender', models.CharField(max_length=255)),
                ('elementary_civil_status', models.CharField(max_length=255)),
                ('elementary_email_address', models.CharField(max_length=255)),
                ('elementary_social_media_accounts', models.CharField(blank=True, max_length=255)),
                ('elementary_mobile_number', models.CharField(max_length=255)),
                ('elementary_landline_number', models.CharField(blank=True, max_length=255)),
                ('elementary_home_address', models.CharField(max_length=255)),
                ('connectivity', models.CharField(default='limited connectivity', max_length=255)),
                ('school_year', models.CharField(default='2020-2021', max_length=255)),
                ('elementary_date_registered', models.DateField(auto_now_add=True)),
                ('elementary_stud_classification', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admission.StudentClassification')),
                ('elementary_stud_grade_level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admission.GradeLevel')),
                ('where_hear_us', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admission.WhereDidYouHearUs')),
                ('why_choose_us', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admission.WhyDidYouChooseUs')),
            ],
        ),
    ]
