# Generated by Django 3.0.5 on 2020-05-01 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0015_auto_20200501_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='SHSstrands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strand_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='seniorhighschool_studentpersonalinformation',
            name='shs_stud_strand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admission.SHSstrands'),
        ),
    ]
