# Generated by Django 3.0.5 on 2020-05-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0017_auto_20200501_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='sy_status',
            field=models.CharField(default='active', max_length=255),
        ),
    ]
