# Generated by Django 3.0.5 on 2020-05-02 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0018_schoolyear_sy_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementary_studentpersonalinformation',
            old_name='school_year',
            new_name='elem_school_year',
        ),
        migrations.RenameField(
            model_name='juniorhighschool_studentpersonalinformation',
            old_name='school_year',
            new_name='jhs_school_year',
        ),
        migrations.RenameField(
            model_name='seniorhighschool_studentpersonalinformation',
            old_name='school_year',
            new_name='shs_school_year',
        ),
        migrations.RenameField(
            model_name='studentpersonalinformation',
            old_name='school_year',
            new_name='stud_school_year',
        ),
    ]
