# Generated by Django 3.0.5 on 2020-05-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0019_auto_20200502_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpersonalinformation',
            name='export_to_CSV',
            field=models.BooleanField(default=False),
        ),
    ]
