# Generated by Django 3.0.5 on 2020-05-06 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0020_studentpersonalinformation_export_to_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission_Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(blank=True)),
                ('appointment_status', models.TextField(default='inactive', max_length=8)),
                ('appointment_count', models.TextField(default='50', max_length=10)),
                ('student_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admission.StudentPersonalInformation')),
            ],
        ),
    ]
