# Generated by Django 3.0.5 on 2020-05-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0022_auto_20200506_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(blank=True)),
                ('appointment_status', models.CharField(default='inactive', max_length=8)),
                ('appointment_count', models.CharField(default='50', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Admission_Appointment',
        ),
    ]
