# Generated by Django 3.0.5 on 2020-05-06 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0023_auto_20200506_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment_dates',
            name='appointment_count',
        ),
        migrations.RemoveField(
            model_name='appointment_dates',
            name='appointment_status',
        ),
        migrations.CreateModel(
            name='Admission_Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_status', models.CharField(default='inactive', max_length=8)),
                ('appointment_count', models.CharField(default='50', max_length=10)),
                ('appointment_date_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admission.Appointment_Dates')),
                ('student_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admission.StudentPersonalInformation')),
            ],
        ),
    ]
