# Generated by Django 3.0.5 on 2020-05-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0024_auto_20200506_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission_appointments',
            name='appointment_count',
        ),
        migrations.RemoveField(
            model_name='admission_appointments',
            name='appointment_status',
        ),
        migrations.AddField(
            model_name='appointment_dates',
            name='appointment_count',
            field=models.CharField(default='50', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment_dates',
            name='appointment_status',
            field=models.CharField(default='inactive', max_length=8),
        ),
    ]
