# Generated by Django 3.0.5 on 2020-05-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0025_auto_20200506_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_dates',
            name='appointment_count',
            field=models.IntegerField(default='50', max_length=10),
        ),
    ]
