# Generated by Django 3.0.5 on 2020-05-06 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0027_auto_20200506_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment_dates',
            name='appointment_count',
        ),
    ]
