# Generated by Django 3.0.5 on 2020-05-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0028_remove_appointment_dates_appointment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_dates',
            name='appointment_count',
            field=models.IntegerField(default=50),
        ),
    ]
