# Generated by Django 3.0.5 on 2020-05-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0029_appointment_dates_appointment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementary_studentpersonalinformation',
            name='reference_no',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
