# Generated by Django 3.0.5 on 2020-05-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0031_auto_20200510_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementary_studentpersonalinformation',
            name='elem_reference_no',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='juniorhighschool_studentpersonalinformation',
            name='jhs_reference_no',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='seniorhighschool_studentpersonalinformation',
            name='shs_reference_no',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentpersonalinformation',
            name='stud_reference_no',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
