# Generated by Django 3.0.5 on 2020-05-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0033_auto_20200510_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpersonalinformation',
            name='stud_reference_no',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
