# Generated by Django 3.0.5 on 2020-05-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0034_studentpersonalinformation_stud_reference_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='seniorhighschool_studentpersonalinformation',
            name='shs_reference_no',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
