# Generated by Django 3.0.5 on 2020-05-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0035_seniorhighschool_studentpersonalinformation_shs_reference_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementary_studentpersonalinformation',
            name='elem_reference_no',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='juniorhighschool_studentpersonalinformation',
            name='jhs_reference_no',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
