# Generated by Django 3.0.5 on 2020-05-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0036_auto_20200511_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlevel',
            name='semester',
            field=models.CharField(default='1st-semester', max_length=50),
        ),
    ]
