# Generated by Django 3.0.5 on 2020-05-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0038_auto_20200514_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferredshift',
            name='shift_title',
            field=models.CharField(max_length=50),
        ),
    ]
