# Generated by Django 3.0.5 on 2020-05-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0040_gradstudentpersonalinformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradstudentpersonalinformation',
            old_name='stud_reference_no',
            new_name='grad_stud_reference_no',
        ),
        migrations.RenameField(
            model_name='gradstudentpersonalinformation',
            old_name='stud_school_year',
            new_name='grad_stud_school_year',
        ),
        migrations.RenameField(
            model_name='gradstudentpersonalinformation',
            old_name='grad_where_hear_us',
            new_name='where_hear_us',
        ),
        migrations.AddField(
            model_name='elementary_studentpersonalinformation',
            name='export_to_CSV',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='juniorhighschool_studentpersonalinformation',
            name='export_to_CSV',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seniorhighschool_studentpersonalinformation',
            name='export_to_CSV',
            field=models.BooleanField(default=False),
        ),
    ]
