# Generated by Django 3.0.5 on 2020-05-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0041_auto_20200515_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementary_studentpersonalinformation',
            name='elementary_date_registered',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gradstudentpersonalinformation',
            name='grad_date_registered',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='juniorhighschool_studentpersonalinformation',
            name='jhs_date_registered',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='seniorhighschool_studentpersonalinformation',
            name='shs_date_registered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
