# Generated by Django 3.0.5 on 2020-05-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0042_auto_20200515_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpersonalinformation',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
